include $(TOPDIR)/rules.mk

PKG_NAME:=luci-theme-neonwrt
PKG_VERSION:=0.1.10
PKG_RELEASE:=1

LUCI_TITLE:=NeonWrt LuCI theme
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
